language: python
sudo: false
cache:
  directories:
  - cache/

before_install:
  - ./get_app_engine_sdk.sh
  - export GAE="./cache/google_appengine"

install:
  - pip install tox

script:
  - tox

env:
  - TOXENV=py27
  - TOXENV=lint
  - TOXENV=lint-test

after_success:
  - tox -e coveralls
